# Use an official Ubuntu base image
FROM ubuntu:latest

# Update and install necessary packages
RUN apt-get update

RUN apt-get install -y perl
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y make
RUN apt-get install -y wget
RUN apt-get install -y bzip2
RUN apt-get install -y libcurl4
RUN apt-get install -y libcurl4-openssl-dev

# Installing gtfToGenePred from source
RUN wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred \
    && chmod +x gtfToGenePred \
    && mv gtfToGenePred /usr/bin/

# Installing gffread from source
RUN apt-get install -y git
RUN cd /usr/bin \
    && git clone https://github.com/gpertea/gffread.git \
    && cd gffread \
    && make 

# Install htslib from source
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libbz2-dev
RUN apt-get install -y liblzma-dev

RUN cd /usr/bin \
    && wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 \
    && tar -vxjf htslib-1.9.tar.bz2 \
    && cd htslib-1.9 \
    && make 

# Set environment variables 
ENV PATH=/usr/bin/perl:/usr/bin/htslib-1.9:/usr/bin/gtfToGenePred:/usr/bin/gffread:$PATH
